# Generated by Django 2.0.1 on 2018-01-17 16:10

from django.db import migrations, models
import photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20180115_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, default='', null=True, validators=[photos.validators.badwords_detector]),
        ),
    ]
